### ISSUE TITLE
Allow upload to HT if NO “Other Data file” was selected. I.e. a pure custom template.

### ISSUE THREAD

**Issue by joeykleingers** [BlueQuartzSoftware/MetaForge#13]

**Comment by imikejackson** [comment]
I would like to see a bit more logic put into this feature/sanity check. For instance, if the model ONLY contains custom entries then we don't care about the "File To Extract Metadata From" but if the model *does* contain other fields then we do care.

Also in the current implementation if you select a Template file and drop in a file to upload, but do not authenticate to HT the "Upload Files" button is still available to be clicked. Either sanity check that we have authenticated to HT or open the HyperThought Dialog box and allow the user to authenticate.

@rcharlesics @joeykleingers @christopro  Thoughts?

**Comment by rcharlesics** [comment]
I'm okay with checking if there is authentication before uploading, but
aren't we unable to upload it there is no location to upload to?

The first sanity check does confuse me. The only time that I would upload
without having another data file is if I only hit add custom values? Do I
not care about the template's values?
