### ISSUE TITLE
Add "command-s" to save a template file and other keyboard shortcuts

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/MetaForge#14]

**Comment by rcharlesics** [comment]
What other keyboard shortcuts are wanted?

**Comment by joeykleingers** [comment]
> What other keyboard shortcuts are wanted?

Open Template: Cmd/Ctrl + O
Open Package: Cmd/Ctrl + Shift + O
Save Template: Cmd/Ctrl + S
Save Package: Cmd/Ctrl + Shift + S
Help: Cmd/Ctrl + H

Note that you may need to pull the latest trunk, because I updated some of the names of these File menu actions.
