### ISSUE TITLE
Ability to write and use custom parsers with the application

### ISSUE THREAD

**Issue by joeykleingers** [BlueQuartzSoftware/MetaForge#18]

**Comment by imikejackson** [comment]
[https://docs.python.org/3/library/abc.html](https://docs.python.org/3/library/abc.html)

[https://docs.python.org/3/library/importlib.html](https://docs.python.org/3/library/importlib.html)

There are examples of basically doing this sort of thing in SIMPL although it is all done through pybind11.

The basic idea is to look in a folder for all .py files maybe using the "load module()" thing
Execute the python file and then look for specific attributes that are needed like are the classes that derive from a specific base class (MetaForgeFileParser for instance). Then does that class implement the needed functions.
+ File extension supported
+ Version of the parser
+ function that returns the dictionary

If the python file passes all of those tests then add it to a list in the UI implementation for use in the UI (same deal for CLI implementations).

**Comment by cryos** [comment]
The `feature/CustomParsers` branch uses the parser API, ensures imported plugin code is derived from the `MetaForgeParser` class and loads the plugin(s) from specified locations. I think that this goes a long way towards addressing this.
