### ISSUE TITLE
Cannot differentiate between files/folders in Select Remote Dialog

### ISSUE THREAD

**Issue by drowenhorst-nrl** [BlueQuartzSoftware/MetaForge#22]
Select a project that has files and folders in a directory.  
All the files show up in the right panel.  Cannot figure out what the directories are.  
Ideal (?): Folders Bold, files plain.  
Completely workable: Only Folders, keep files invisible.

**Comment by imikejackson** [comment]
There are now 2 columns with the "Name" and "Kind". You cannot select files. You can select directories. I wasn't sure if you wanted to hide files and only show folders so I just went this route.

@drowenhorst-nrl please comment on this solution

**Comment by drowenhorst-nrl** [comment]
It might be best in the next version to only have folders.  Bad things may happen if you drop into a folder with 1000 tomo tiffs.
