### ISSUE TITLE
Repainting the user interface after certain changes take place

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/MetaForge#31]
Seems that PySide2 needs to have some extra "repaint()" or "update()" or refresh() or something called after certain UI elements are changed. This can lead to a lot of user confusion during operation because the user will think they did something but get no feedback from the UI and then try the same thing again.

**Comment by imikejackson** [comment]
I have been able to reproduce on MacOS, Windows 10 and Linux.

**Comment by christopro** [comment]
Is this a case of data in one of the models changing without a `dataChanged` signal being emitted? What is the step by step scenario to reproduce this? What UI elements are not being updated correctly?

**Comment by imikejackson** [comment]
In the HyperThoughtDialogImp.py file comment out lines 58,59 and 60. Then using the "Key" button to paste what ever is on your clipboard. If nothing appears, then just try to resize the dialog and then the pasted content appears.

**Comment by imikejackson** [comment]
I was able to reproduce on Windows 10 and MacOS and I have seen it happen on Raheem's screen. I'm just not sure what the underlying issue is.

**Comment by imikejackson** [comment]
[https://bugreports.qt.io/browse/QTBUG-68740](https://bugreports.qt.io/browse/QTBUG-68740) looks like was not really fixed.

Using the "Fusion" style or applying our own style helps fix the issue.

**Comment by imikejackson** [comment]
#12 is related to this bug. By implementing a style this issue will be fixed.

**Comment by imikejackson** [comment]
Fixed if using the "Dark Visual Style" on macOS
