### ISSUE TITLE
Templates cleared when opening a new file to parse

### ISSUE THREAD

**Issue by drowenhorst-nrl** [BlueQuartzSoftware/MetaForge#56]
This is not an easy use case to address, but I think it will likely be worth it.  In create template: load a template (tempA.ez) that contains a mixture of source and custom fields, initially created with "dataset1.h5".  Then open/drag&drop "dataset2.h5" ... all fields get cleared out and replaced with the new dataset fields, including customizations.  

Is it possible in this situation to look at which Source trees are identical from the original template and the newly parsed datafile, and keep any customizations.  Also keep all custom fields.  

Any fields that are in the template from the original datafile, but not found in the new data file should also be kept (stretch goal: highlight them?). Upon parsing on "Use Template", the unfound fields values are filled with empty strings.

**Comment by joeykleingers** [comment]
Goal would be to be able to "build" a template based on multiple incompatible data file types.
