### ISSUE TITLE
Parse units from ANG/CTF to put into parsed Dictionary and annotations

### ISSUE THREAD

**Issue by joeykleingers** [BlueQuartzSoftware/MetaForge#6]

**Comment by imikejackson** [comment]
Add phase # to annotation

Laue class to annotation

**Comment by imikejackson** [comment]
Include units from other kinds of files.
+ Key, Value, units, annotation(Comments)

Update parsers to return that quad set. ANG/CTF would be good test beds for this.

Update the uploader to use a threaded layer with refresh token. Same way as HyperDrive.

+ Want to be able to allow other platforms to re-use MetaForge ideas/infrastructure.
